src/Entity/Logement.php
<?php

namespace App\Entity;

use App\Repository\LogementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LogementRepository::class)]
class Logement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column]
    private ?int $commission = null;
 
    #[ORM\Column]
    private ?int $menage = null;

    /**
     * @var Collection<int, Reservation>
     */
    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'logement_id')]
    private Collection $logement_id;

    /**
     * @var Collection<int, Intervention>
     */
    #[ORM\OneToMany(mappedBy: 'logement', targetEntity: Intervention::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $interventions;

    /**
     * @var Collection<int, Consommable>
     */
    #[ORM\OneToMany(mappedBy: 'logement', targetEntity: Consommable::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $consommables;

    /**
     * @var Collection<int, Reservation>
     */
    #[ORM\OneToMany(mappedBy: 'logement', targetEntity: Reservation::class, cascade: ['remove'], orphanRemoval: true)]
private Collection $reservations;


    /**
     * @var Collection<int, Test>
     */
    #[ORM\OneToMany(targetEntity: Test::class, mappedBy: 'logement')]
    private Collection $tests;
    

    public function __construct()
    {
        $this->logement_id = new ArrayCollection();
        $this->interventions = new ArrayCollection();
        $this->consommables = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->tests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getCommission(): ?int
    {
        return $this->commission;
    }

    public function setCommission(int $commission): static
    {
        $this->commission = $commission;

        return $this;
    }

    public function getMenage(): ?int
    {
        return $this->menage;
    }

    public function setMenage(int $menage): static
    {
        $this->menage = $menage;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getLogementId(): Collection
    {
        return $this->logement_id;
    }

    public function addLogementId(Reservation $logementId): static
    {
        if (!$this->logement_id->contains($logementId)) {
            $this->logement_id->add($logementId);
            $logementId->setLogementId($this);
        }

        return $this;
    }

    public function removeLogementId(Reservation $logementId): static
    {
        if ($this->logement_id->removeElement($logementId)) {
            // set the owning side to null (unless already changed)
            if ($logementId->getLogementId() === $this) {
                $logementId->setLogementId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Intervention>
     */
    public function getInterventions(): Collection
    {
        return $this->interventions;
    }

    public function addIntervention(Intervention $intervention): static
    {
        if (!$this->interventions->contains($intervention)) {
            $this->interventions->add($intervention);
            $intervention->setLogementId($this);
        }

        return $this;
    }

    public function removeIntervention(Intervention $intervention): static
    {
        if ($this->interventions->removeElement($intervention)) {
            // set the owning side to null (unless already changed)
            if ($intervention->getLogementId() === $this) {
                $intervention->setLogementId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Consommable>
     */
    public function getConsommables(): Collection
    {
        return $this->consommables;
    }

    public function addConsommable(Consommable $consommable): static
    {
        if (!$this->consommables->contains($consommable)) {
            $this->consommables->add($consommable);
            $consommable->setLogementId($this);
        }

        return $this;
    }

    public function removeConsommable(Consommable $consommable): static
    {
        if ($this->consommables->removeElement($consommable)) {
            // set the owning side to null (unless already changed)
            if ($consommable->getLogementId() === $this) {
                $consommable->setLogementId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setLogementId($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getLogementId() === $this) {
                $reservation->setLogementId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Test>
     */
    public function getTests(): Collection
    {
        return $this->tests;
    }

    public function addTest(Test $test): static
    {
        if (!$this->tests->contains($test)) {
            $this->tests->add($test);
            $test->setLogement($this);
        }

        return $this;
    }

    public function removeTest(Test $test): static
    {
        if ($this->tests->removeElement($test)) {
            // set the owning side to null (unless already changed)
            if ($test->getLogement() === $this) {
                $test->setLogement(null);
            }
        }

        return $this;
    }
    public function getInformation(): array
    {
        return[
            'id' => $this->getId(),
            'Nom' => $this->getNom(),
            'Commission'=> $this->getCommission(),
            'Menage'=> $this->getMenage(),
        ];
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom_voyageur = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    private ?Logement $logement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomVoyageur(): ?string
    {
        return $this->Nom_voyageur;
    }

    public function setNomVoyageur(string $Nom_voyageur): static
    {
        $this->Nom_voyageur = $Nom_voyageur;
        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): static
    {
        $this->prix = $prix;
        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;
        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;
        return $this;
    }

    public function getLogement(): ?Logement
    {
        return $this->logement;
    }

    public function setLogement(?Logement $logement): static
    {
        $this->logement = $logement;
        return $this;
    }
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
private ?string $plateforme = null;

public function getPlateforme(): ?string
{
    return $this->plateforme;
}

public function setPlateforme(?string $plateforme): self
{
    $this->plateforme = $plateforme;
    return $this;
}


    public function getInformation(): array
    {
        return [
            'id' => $this->getId(),
            'Nom_voyageur' => $this->getNomVoyageur(),
            'Plateforme' => $this->getPlateforme(),
            'date_debut'=> $this->getDate()->format('d-m-Y'),
            'date_fin'=> $this->getDateFin()->format('d-m-Y'),
            'prix'=> $this->getPrix(),
            'logement'=> $this->getLogement()->getNom(),
        ];
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Logement;
use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormError;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom_voyageur')
            ->add('prix')
            ->add('date', null, [
                'widget' => 'single_text',
            ])
            ->add('date_fin', null, [
                'widget' => 'single_text',
            ])
            ->add('logement', EntityType::class, [
                'class' => Logement::class,
                'choice_label' => 'nom',
            ])
        ;

        // Ajout de l'écouteur d'événement pour la validation
        $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
            $form = $event->getForm();
            $data = $event->getData();

            if ($data->getDate() > $data->getDateFin()) {
                $form->get('date_fin')->addError(new FormError('La date de fin ne peut pas être antérieure à la date de début.'));
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\service\ReservationService;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Repository\LogementRepository;

#[Route('/reservation')]
final class ReservationController extends AbstractController
{
    #[Route(name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/api/findAll', name: 'apiJson3', methods: ['GET'])]
    public function api(Reservationservice $Reservationservice)
    {
        return new JsonResponse($Reservationservice->getAllReservation(),Response::HTTP_OK);
    }

    #[Route('/api/add', name: 'api_add_reservation', methods: ['POST'])]
    public function addReservation(Request $request, EntityManagerInterface $entityManager, \App\Repository\LogementRepository $logementRepository): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
    
        if (
            !$data || 
            !isset($data['Nom_voyageur'], $data['date_debut'], $data['date_fin'], $data['prix'], $data['logement'], $data['plateforme'])
        ) {
            return new JsonResponse(['error' => 'Données incomplètes ou invalides'], Response::HTTP_BAD_REQUEST);
        }
    
        $reservation = new Reservation();
        $reservation->setNomVoyageur($data['Nom_voyageur']);
        $reservation->setPlateforme($data['plateforme']); // ✅
    
        try {
            $reservation->setDate(new \DateTime($data['date_debut']));
            $reservation->setDateFin(new \DateTime($data['date_fin']));
        } catch (\Exception $e) {
            return new JsonResponse(['error' => 'Format de date invalide'], Response::HTTP_BAD_REQUEST);
        }
    
        $reservation->setPrix($data['prix']);
    
        $logement = $logementRepository->find($data['logement']);
        if (!$logement) {
            return new JsonResponse(['error' => 'Logement non trouvé'], Response::HTTP_NOT_FOUND);
        }
    
        $reservation->setLogement($logement);
    
        $entityManager->persist($reservation);
        $entityManager->flush();
    
        return new JsonResponse(['message' => 'Réservation ajoutée avec succès'], Response::HTTP_CREATED);
    }
    

    #[Route('/api/update/{id}', name: 'api_reservation_update', methods: ['PUT'])]
    public function updateReservation(
        Request $request,
        Reservation $reservation,
        EntityManagerInterface $em,
        LogementRepository $logementRepo
    ): JsonResponse {
        $data = json_decode($request->getContent(), true);
    
        if (!isset($data['Nom_voyageur'], $data['date'], $data['date_fin'], $data['prix'], $data['logement'], $data['plateforme'])) {
            return new JsonResponse(['error' => 'Données incomplètes'], Response::HTTP_BAD_REQUEST);
        }
    
        $reservation->setNomVoyageur($data['Nom_voyageur']);
        $reservation->setPlateforme($data['plateforme']); // ✅
        $reservation->setDate(new \DateTime($data['date']));
        $reservation->setDateFin(new \DateTime($data['date_fin']));
        $reservation->setPrix($data['prix']);
    
        $logement = $logementRepo->find($data['logement']);
        if (!$logement) {
            return new JsonResponse(['error' => 'Logement introuvable'], Response::HTTP_NOT_FOUND);
        }
    
        $reservation->setLogement($logement);
        $em->flush();
    
        return new JsonResponse(['message' => 'Réservation mise à jour']);
    }
    




#[Route('/api/delete/{id}', name: 'api_reservation_delete', methods: ['DELETE'])]
public function deleteReservation(
    Reservation $reservation,
    EntityManagerInterface $em
): JsonResponse {
    $em->remove($reservation);
    $em->flush();

    return new JsonResponse(['message' => 'Réservation supprimée']);
}

}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservations{% endblock %}

{% block stylesheets %}
<style>
    body {
        background-color: #f8f9fa;
        font-family: 'Arial', sans-serif;
    }

    h1 {
        color: #343a40;
        font-size: 2.5rem;
        font-weight: bold;
    }

    .table {
        background-color: #fff;
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .table th {
        background-color: #343a40;
        color: #fff;
        text-align: center;
    }

    .table td {
        text-align: center;
        vertical-align: middle;
    }

    .btn {
        border-radius: 5px;
        padding: 5px 10px;
        font-size: 0.9rem;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #004085;
    }

    .btn-warning {
        background-color: #ffc107;
        border-color: #ffc107;
        color: #343a40;
    }

    .btn-warning:hover {
        background-color: #e0a800;
        border-color: #d39e00;
    }

    .btn-success {
        background-color: #28a745;
        border-color: #28a745;
    }

    .btn-success:hover {
        background-color: #218838;
        border-color: #1e7e34;
    }

    .text-end {
        margin-top: 20px;
    }
</style>
{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4 text-center">Reservations</h1>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Logement</th>
                <th scope="col">Voyageur</th>
                <th scope="col">Prix</th>
                <th scope="col">Date</th>
                <th scope="col">Date Fin</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.logement.nom }}</td>
                    <td>{{ reservation.NomVoyageur }}</td>
                    <td>{{ reservation.prix | number_format(2, ',', ' ') }} €</td>
                    <td>{{ reservation.date ? reservation.date|date('d/m/Y') : 'N/A' }}</td>
                    <td>{{ reservation.dateFin ? reservation.dateFin|date('d/m/Y') : 'N/A' }}</td>
                    <td>
                        <a href="{{ path('app_reservation_show', {'id': reservation.id}) }}" class="btn btn-primary btn-sm">Voir</a>
                        <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}" class="btn btn-warning btn-sm">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9" class="text-center">Aucune réservation trouvée.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="text-end">
        <a href="{{ path('app_reservation_new') }}" class="btn btn-success">Créer une nouvelle réservation</a>
    </div>
</div>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Nom_voyageur</th>
                <td>{{ reservation.NomVoyageur }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ reservation.prix }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Commission</th>
                <td>{{ reservation.commission }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ reservation.dateFin ? reservation.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Menage</th>
                <td>{{ reservation.menage }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}